
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderservice
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true